### ISSUE TITLE
localmemcache on travis-ci fails

### ISSUE THREAD

**Issue by minad** [sck/localmemcache#4]
See https://github.com/minad/juno/issues/4

The problem is that mmap fails. Travis seems to be 32 bit. Is this the problem?

**Comment by sck** [comment]
Do you get an error message?  32 bit just limits the size of the virtual adress space (3GB)

**Comment by minad** [comment]
@sck: Well I know. I get the error, that mmap fails, cannot allocate memory. It seems that just the syscall fails. But no more information. Therefore I am asking. If the error would be more meaningful I could resolve it by myself :)

**Comment by leucos** [comment]
Stumbling on this too.
Here is a failed build : https://travis-ci.org/leucos/ramaze/jobs/6064667
This is a Ramaze build, but it happends in a LocalMemCache test. 
I tried chmoding `/dev/shm` without success.

**Comment by sck** [comment]
Hey leucos,

this usually happens when you've run localmemcache as root in the beginning and then switched to a user with less permissions.  The default directory where lmc sotres its files is: /var/tmp/localmemcache

You might to chmod or just remove the directory, so it can be created again.  Let me know if that works for you.
The error message should have been more descriptive. :)

**Comment by leucos** [comment]
Thanks for your comment @sck. I made a few attempts on Travis an got no results.

It seems to fail since travis CI changed their environment and the underlying Travis box is 64bits.

Not sure it is related to existing directories : when I remove the first test (that pass), the second still fails. But on a local 64bits box, no problem though. Puzzling.
